name: build
on: [push, pull_request]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-compiler: [ '4.04.0', '4.11.0' ]
    env:
      OPAMCLI: 2.1
      OPAMCONFIRMLEVEL: unsafe-yes
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - run: opam pin -n .
    - run: opam install tiny_httpd
    - run: opam install tiny_httpd_camlzip
    - run: opam depext -yt tiny_httpd tiny_httpd_camlzip
    - run: opam reinstall -t tiny_httpd
    - run: opam reinstall -t tiny_httpd_camlzip
    - run: opam remove tiny_httpd tiny_httpd_camlzip
    - run: opam exec -- dune build @install @runtest
